In [94]:
import cv2
import numpy as np
from torchvision import transforms

def get_frames(filename, n_frames=3):
    frames = []
    v_cap = cv2.VideoCapture(filename)
    v_len = int(v_cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frame_list = np.linspace(0, v_len - 1, v_len // n_frames, dtype=np.int16)

    for fn in range(v_len):
        success, frame = v_cap.read()
        if not success:
            continue
        if fn in frame_list:
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            asarray = np.asarray(frame)
            frames.append(asarray)

    v_cap.release()
    # Change dimensions to Frames x Channel x Height x Width
    np_asarray = np.transpose(np.asarray(frames),  (0,3,2,1))
    return np_asarray,  v_len


In [95]:
frames, length = get_frames("data/passes/pass260.mp4")
print(frames.shape)
print(frames[0])

(17, 3, 1280, 720)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [75]:
np.linspace(0, 63, 18, dtype=np.int16)

array([ 0,  3,  7, 11, 14, 18, 22, 25, 29, 33, 37, 40, 44, 48, 51, 55, 59,
       63], dtype=int16)

In [101]:
from PIL import Image
data_transform = transforms.Compose([
    transforms.Resize((720, 720)),
    transforms.ToTensor(),

    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225]),
])

image =  Image.fromarray(frames[10].T, "RGB")
new_frames = data_transform(image)
tensor_to_pil = transforms.ToPILImage()(new_frames.squeeze_(0))
# new_frames
image.show()
tensor_to_pil.show()